### ISSUE TITLE
Export to Arxiv

### ISSUE THREAD

**Issue by s2t2** [gw-ospo/quarto-manuscript-template#1]
Use the journal formatter plugin to export to arxiv.

```yml
format:
  html: default
    #theme: solar
  #docx: default
  jats: default
  pdf: default

  #
  # JOURNAL FORMATS:
  # https://quarto.org/docs/extensions/listing-journals.html
  #
  # https://github.com/mikemahoney218/quarto-arxiv
  # quarto install extension mikemahoney218/quarto-arxiv
  #arxiv-pdf:
  #  keep-tex: true
```
